toolbar:
  - styleselect | bold italic | undo redo | formatselect | paste | fullscreen
  - alignleft aligncenter alignright alignjustify | bullist numlist outdent indent
  - image | link
  - file | edit | view | insert | format | tools
plugins:
  - lists
  - paste
  - image
  - link
  - code
  - table
  - wordcount
  - autoresize
  - fullscreen
images_upload_url: '/uploader/image'
autoresize_min_height: 350
relative_urls : false
remove_script_host : false
convert_urls : true